#!/usr/bin/python3

une_exception = 10
